In [2]:
# requests library handles the HTTP methods and requests for Python
import pandas as pd
import time
import re
import requests
from bs4 import BeautifulSoup
import random
url ='https://air-quality-by-api-ninjas.p.rapidapi.com/v1/airquality'

headers = {
    'X-RapidAPI-Host': 'air-quality-by-api-ninjas.p.rapidapi.com',
    'X-RapidAPI-Key': '39bef7d171msh47b87402a02c35bp1d3674jsn9bc769a834e7'
  }

params = {'city':['Dublin','Amsterdam','Madrid','Paris','Berlin','Milan','London','Barcelona','Frankfurt','Lisbon'] }


cities = []
overall_row = []
count=10

for city in params.values():
    for subcity in city:
        count=count-1
        print("Loading....",count)
        #request to api
        air = requests.get(url,headers = headers,params = {'city': subcity})
        
        #Change response to json and dict format
        dic_air_json = air.json()
        
        #Convert dictionary to list
        listair = list(dic_air_json.values())
        
        #overall dic value to list
        overall_row.append(listair[6])
        
        # city to list
        cities.append(subcity)
df_cities = pd.DataFrame({'City':cities}) 
df_overall = pd.DataFrame({'Air_Quality_index_overall':overall_row})
maind_aqi = pd.concat([df_cities,df_overall],axis=1)
maind_aqi

Loading.... 9
Loading.... 8
Loading.... 7
Loading.... 6
Loading.... 5
Loading.... 4
Loading.... 3
Loading.... 2
Loading.... 1
Loading.... 0

        City  Air_Quality_index_overall
0     Dublin                         57
1  Amsterdam                        159
2     Madrid                        141
3      Paris                        198
4     Berlin                        152
5      Milan                        198
6     London                        184
7  Barcelona                        204
8  Frankfurt                        141
9     Lisbon                        203